force-app/main/default/objects/Accommodation__c/Accommodation__c.object-meta.xml
<CustomObject>
    <label>Accommodation</label>
    <nameField>
        <label>Accommodation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accommodations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accommodation__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Finalizing Dates</fullName>
            </value>
            <value>
                <fullName>Booking Transportation</fullName>
            </value>
            <value>
                <fullName>Booking Accommodations</fullName>
            </value>
            <value>
                <fullName>Booking Activities</fullName>
            </value>
            <value>
                <fullName>Booking Restaurants</fullName>
            </value>
            <value>
                <fullName>Finalizing Trip</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Accommodation__c/Trip_Accommodation__c.object-meta.xml
<CustomObject>
    <label>Trip Accommodation</label>
    <nameField>
        <label>Trip Accommodation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Accommodations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Accommodation__c/fields/Accommodation__c.field-meta.xml
<CustomField>
    <fullName>Accommodation__c</fullName>
    <label>Accommodation</label>
    <referenceTo>Accommodation__c</referenceTo>
    <relationshipLabel>Trip Accommodations</relationshipLabel>
    <relationshipName>Trip_Accommodations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip_Accommodation__c/fields/Accommodation_Address__c.field-meta.xml
<CustomField>
    <fullName>Accommodation_Address__c</fullName>
    <label>Accommodation Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trip_Accommodation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Accommodation__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Accommodations</relationshipLabel>
    <relationshipName>Trip_Accommodations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip_Day__c/Trip_Day__c.object-meta.xml
<CustomObject>
    <label>Trip Day</label>
    <nameField>
        <label>Trip Day Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Day__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
                <default>true</default>
                <label>Planning</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Day__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Days</relationshipLabel>
    <relationshipName>Trip_Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip_Day__c/fields/Trip_Accommodation__c.field-meta.xml
<CustomField>
    <fullName>Trip_Accommodation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip Accommodation</label>
    <referenceTo>Trip_Accommodation__c</referenceTo>
    <relationshipLabel>Trip Days</relationshipLabel>
    <relationshipName>Trip_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TripAccommodationTriggerHandler.cls
// Author: Coltin Lappin-Lux
// Date: 9/20/2022

public without sharing class TripAccommodationTriggerHandler {
    // ---------------------------------------------------------
    // Trigger Contexts
    // ---------------------------------------------------------
    public static void beforeInsert(List<Trip_Accommodation__c> newTripAccommodations){
        updateAddress(newTripAccommodations);
    }

    public static void beforeUpdate(Map<Id, Trip_Accommodation__c> newTripAccommodationsMap, Map<Id, Trip_Accommodation__c> oldTripAccommodationsMap){
        updateAddress(newTripAccommodationsMap, oldTripAccommodationsMap);
    }

    public static void afterInsert(Map<Id, Trip_Accommodation__c> newTripAccommodationsMap){
        associateToTripDay(newTripAccommodationsMap, new Map<Id, Trip_Accommodation__c>());
    }

    public static void afterUpdate(Map<Id, Trip_Accommodation__c> newTripAccommodationsMap, Map<Id, Trip_Accommodation__c> oldTripAccommodationsMap){
        associateToTripDay(newTripAccommodationsMap, oldTripAccommodationsMap);
    }

    public static void updateAddress(List<Trip_Accommodation__c> newTripAccommodations){
        Set<Id> accommodationIdSet = new Set<Id>();
        for(Trip_Accommodation__c tripAccRecord : newTripAccommodations){
            if(tripAccRecord.Accommodation__c != null){
                accommodationIdSet.add(tripAccRecord.Accommodation__c);
            }
        }

        List<Accommodation__c> accList = [SELECT Id, Address__c FROM Accommodation__c WHERE Id IN :accommodationIdSet];
        Map<Id, Accommodation__c> addressMap = new Map<Id, Accommodation__c>(accList);

        for(Trip_Accommodation__c tripAccRecord : newTripAccommodations){
            if(tripAccRecord.Accommodation__c != null){
                Id accId = tripAccRecord.Accommodation__c;
                if(addressMap.containsKey(accId)){
                    String addressValue = addressMap.get(accId).Address__c;
                    tripAccRecord.Accommodation_Address__c = addressValue;
                }
            }
        }
    }

    public static void updateAddress(Map<Id, Trip_Accommodation__c> newTripAccommodationsMap, Map<Id, Trip_Accommodation__c> oldTripAccommodationsMap){
        List<Trip_Accommodation__c> newTripAccommodationsList = new List<Trip_Accommodation__c>();
        for(Id tripAccId : newTripAccommodationsMap.keySet()){
            Trip_Accommodation__c tripAccRecord = newTripAccommodationsMap.get(tripAccId);
            if(oldTripAccommodationsMap.containsKey(tripAccId)){
                Trip_Accommodation__c oldTripAccRecord = oldTripAccommodationsMap.get(tripAccId);
                if(oldTripAccRecord.Accommodation__c != tripAccRecord.Accommodation__c){
                    newTripAccommodationsList.add(tripAccRecord);
                } else if(oldTripAccRecord.Status__c != tripAccRecord.Status__c){
                    newTripAccommodationsList.add(tripAccRecord);
                }
            } else {
                newTripAccommodationsList.add(tripAccRecord);
            }
        }
        updateAddress(newTripAccommodationsList);
    }

    // ---------------------------------------------------------
    // Relate to Trip Day Records
    // ---------------------------------------------------------
    public static void associateToTripDay(Map<Id, Trip_Accommodation__c> newTripAccommodationsMap, Map<Id, Trip_Accommodation__c> oldTripAccommodationsMap){
        Map<Id, List<Trip_Accommodation__c>> tripToAccMap = new Map<Id, List<Trip_Accommodation__c>>();
        for(Id tripAccId : newTripAccommodationsMap.keySet()){
            Trip_Accommodation__c newTripAccRecord = newTripAccommodationsMap.get(tripAccId);
            if(newTripAccRecord.Trip__c != null){
                Id tripId = newTripAccRecord.Trip__c;
                if(oldTripAccommodationsMap.containsKey(tripAccId)){
                    Trip_Accommodation__c oldTripAccRecord = oldTripAccommodationsMap.get(tripAccId);
                    if(newTripAccRecord.Status__c != oldTripAccRecord.Status__c && newTripAccRecord.Status__c == 'Booked'){
                        List<Trip_Accommodation__c> tempList = tripToAccMap.containsKey(tripId) ? tripToAccMap.get(tripId) : new List<Trip_Accommodation__c>();
                        tempList.add(newTripAccRecord);
                        tripToAccMap.put(tripId, tempList);
                    }
                } else {
                    List<Trip_Accommodation__c> tempList = tripToAccMap.containsKey(tripId) ? tripToAccMap.get(tripId) : new List<Trip_Accommodation__c>();
                    tempList.add(newTripAccRecord);
                    tripToAccMap.put(tripId, tempList);
                }
            }
        }

        List<Trip_Day__c> tripDaysToUpdate = new List<Trip_Day__c>();
        for(Trip_Day__c tripDayRecord : [SELECT Id, Name, Date__c, Trip__c, Trip_Accommodation__c FROM Trip_Day__c WHERE Trip__c IN :tripToAccMap.keySet()]){
            Id tripId = tripDayRecord.Trip__c;
            List<Trip_Accommodation__c> accommodationsList = tripToAccMap.containsKey(tripId) ? tripToAccMap.get(tripId) : new List<Trip_Accommodation__c>();
            for(Trip_Accommodation__c tripAccRecord : accommodationsList){
                if(Date.valueOf(tripAccRecord.Check_In__c) <= tripDayRecord.Date__c && tripDayRecord.Date__c < Date.valueOf(tripAccRecord.Check_Out__c)){
                    tripDayRecord.Trip_Accommodation__c = tripAccRecord.Id;
                    tripDaysToUpdate.add(tripDayRecord);
                }
            }
        }

        update tripDaysToUpdate;
    }
}