force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Activity__c/Trip_Activity__c.object-meta.xml
<CustomObject>
    <label>Trip Activity</label>
    <nameField>
        <label>Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Activity__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <formula>IF(WEEKDAY(Date__c) == 1, &apos;Sunday&apos;,
IF(WEEKDAY(Date__c) == 2, &apos;Monday&apos;,
IF(WEEKDAY(Date__c) == 3, &apos;Tuesday&apos;,
IF(WEEKDAY(Date__c) == 4, &apos;Wednesday&apos;,
IF(WEEKDAY(Date__c) == 5, &apos;Thursday&apos;,
IF(WEEKDAY(Date__c) == 6, &apos;Friday&apos;,
IF(WEEKDAY(Date__c) == 7, &apos;Saturday&apos;, &apos;Unknown&apos;
)))))))</formula>
    <label>Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip_Activity__c/fields/Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_Hours__c</fullName>
    <label>Duration (Hours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip_Activity__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Activities</relationshipLabel>
    <relationshipName>Trip_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Activity__c/fields/Trip_Day__c.field-meta.xml
<CustomField>
    <fullName>Trip_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip Day</label>
    <referenceTo>Trip_Day__c</referenceTo>
    <relationshipLabel>Trip Activities</relationshipLabel>
    <relationshipName>Trip_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Day__c/Trip_Day__c.object-meta.xml
<CustomObject>
    <label>Trip Day</label>
    <nameField>
        <label>Trip Day Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Day__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Days</relationshipLabel>
    <relationshipName>Trip_Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TripAssistantController.cls
// Author: Coltin Lappin-Lux
// Date: 9/30/2022

public without sharing class TripAssistantController {
    @AuraEnabled
    public static List<Trip_Day__c> getTripDays(Id tripId){
        List<Trip_Day__c> tripDays = [SELECT Id, Name, Day__c, Location__c, (SELECT Id, Name, Area__c, Duration_Hours__c, RecordTypeId, RecordType.Name FROM Trip_Activities__r) FROM Trip_Day__c WHERE Trip__c = :tripId];

        return tripDays;
    }

    @AuraEnabled
    public static List<Trip_Activity__c> getActivitiesWithoutTripDays(Id tripId){
        List<Trip_Activity__c> activitiesWithoutDays = [SELECT Id, Name, Area__c, Duration_Hours__c, RecordTypeId, RecordType.Name FROM Trip_Activity__c WHERE Trip__c = :tripId];

        return activitiesWithoutDays;
    }
}